### ISSUE TITLE
Out of bound write in jpc_dec_decodecblk

### ISSUE THREAD

**Issue by adarshdinesh** [jasper-software/jasper#123]
gdb-peda$ r out_of_bound_write 
Starting program: /home/sandbox/Desktop/fuzz/bin out_of_bound_write
warning: trailing garbage in marker segment (40 bytes)
warning: ignoring trailing garbage (148 bytes)
warning: ignoring trailing garbage (62 bytes)
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol

Program received signal SIGSEGV, Segmentation fault.

gdb-peda$ backtrace 10
#0  _int_malloc (av=av@entry=0x7ffff784fb20 <main_arena>, bytes=bytes@entry=0x12c) at malloc.c:3514
#1  0x00007ffff750f5d4 in __GI___libc_malloc (bytes=0x12c) at malloc.c:2911
#2  0x00007ffff7508d07 in __GI__IO_str_overflow (fp=0x7fffffffd920, c=0x74) at strops.c:107
#3  0x00007ffff75076b0 in __GI__IO_default_xsputn (f=0x7fffffffd920, data=<optimized out>, n=0x18) at genops.c:455
#4  0x00007ffff74da50b in _IO_vfprintf_internal (s=s@entry=0x7fffffffd920, format=<optimized out>, 
    format@entry=0x7ffff761b658 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", ap=ap@entry=0x7fffffffda48) at vfprintf.c:1632
#5  0x00007ffff7502773 in _IO_vasprintf (result_ptr=0x7fffffffdb68, format=0x7ffff761b658 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    args=args@entry=0x7fffffffda48) at vasprintf.c:59
#6  0x00007ffff74e1a57 in ___asprintf (string_ptr=string_ptr@entry=0x7fffffffdb68, 
    format=format@entry=0x7ffff761b658 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n") at asprintf.c:35
#7  0x00007ffff74b9b2f in __assert_fail_base (fmt=0x7ffff761b658 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff7bc1e32 "seg->type == JPC_SEG_RAW", 
    file=file@entry=0x7ffff7bc1dc0 "/home/sandbox/jasper/src/libjasper/jpc/jpc_t1dec.c", line=line@entry=0x134, 
    function=function@entry=0x7ffff7bc1f70 <__PRETTY_FUNCTION__.6346> "jpc_dec_decodecblk") at assert.c:57
#8  0x00007ffff74b9c82 in __GI___assert_fail (assertion=0x7ffff7bc1e32 "seg->type == JPC_SEG_RAW", 
    file=0x7ffff7bc1dc0 "/home/sandbox/jasper/src/libjasper/jpc/jpc_t1dec.c", line=0x134, 
    function=0x7ffff7bc1f70 <__PRETTY_FUNCTION__.6346> "jpc_dec_decodecblk") at assert.c:101
#9  0x00007ffff7ba2352 in jpc_dec_decodecblk () from /usr/lib/libjasper.so.4
(More stack frames follow...)

[out_of_bound_write.zip](https://github.com/mdadams/jasper/files/870028/out_of_bound_write.zip)

**Comment by adarshdinesh** [comment]
Looks like some heap related issue. Interestingly this crashes from inside Libc malloc

**Comment by asarubbo** [comment]
Your testcase under asan returns me the same stacktrace of the issue you already reported ( #124) which, as said there, has the same root cause of #90 

Since there are some reported bugs, I'd suggest to compare the asan stacktrace that can help immediately to define if is a duplicate of something already reported.

**Comment by asarubbo** [comment]
FTR, this is what happens with your testcase under asan:
```
==1287==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61f000000cf8 at pc 0x7f78a41615d6 bp 0x7ffc5fab24a0 sp 0x7ffc5fab2498                                                       
WRITE of size 8 at 0x61f000000cf8 thread T0                                                                                                                                                    
    #0 0x7f78a41615d5 in dec_clnpass /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_t1dec.c:869:4                                                              
    #1 0x7f78a4147762 in jpc_dec_decodecblk /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_t1dec.c:283:11                                                      
    #2 0x7f78a413e77d in jpc_dec_decodecblks /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_t1dec.c:177:11                                                     
    #3 0x7f78a409328e in jpc_dec_tiledecode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:1085:6                                                        
    #4 0x7f78a4074961 in jpc_dec_process_sod /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:658:7                                                        
    #5 0x7f78a407fa85 in jpc_dec_decode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:425:10                                                            
    #6 0x7f78a407fa85 in jpc_decode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:262                                                                   
    #7 0x7f78a3ff5238 in jas_image_decode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/base/jas_image.c:444:16                                                       
    #8 0x511ce4 in main /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/appl/imginfo.c:238:16                                                                                     
    #9 0x7f78a2f9078f in __libc_start_main /tmp/portage/sys-libs/glibc-2.23-r3/work/glibc-2.23/csu/../csu/libc-start.c:289                                                                     
    #10 0x419d88 in _start (/usr/bin/imginfo+0x419d88)                                                                                                                                         

0x61f000000cf8 is located 72 bytes to the right of 3120-byte region [0x61f000000080,0x61f000000cb0)
allocated by thread T0 here:
    #0 0x4d9458 in malloc /tmp/portage/sys-libs/compiler-rt-sanitizers-4.0.0/work/compiler-rt-4.0.0.src/lib/asan/asan_malloc_linux.cc:66
    #1 0x7f78a400d5e5 in jas_matrix_create /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/base/jas_seq.c:139:25
    #2 0x7f78a400d044 in jas_seq2d_create /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/base/jas_seq.c:92:17
    #3 0x7f78a40886a0 in jpc_dec_tileinit /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:737:23
    #4 0x7f78a40755f1 in jpc_dec_process_sod /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:594:7
    #5 0x7f78a407fa85 in jpc_dec_decode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:425:10
    #6 0x7f78a407fa85 in jpc_decode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_dec.c:262
    #7 0x7f78a3ff5238 in jas_image_decode /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/base/jas_image.c:444:16
    #8 0x511ce4 in main /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/appl/imginfo.c:238:16
    #9 0x7f78a2f9078f in __libc_start_main /tmp/portage/sys-libs/glibc-2.23-r3/work/glibc-2.23/csu/../csu/libc-start.c:289

SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/portage/media-libs/jasper-2.0.10/work/jasper-2.0.10/src/libjasper/jpc/jpc_t1dec.c:869:4 in dec_clnpass
Shadow bytes around the buggy address:
  0x0c3e7fff8140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff8150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff8160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff8170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff8180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3e7fff8190: 00 00 00 00 00 00 fa fa fa fa fa fa fa fa fa[fa]
  0x0c3e7fff81a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff81b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff81c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff81d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff81e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1287==ABORTING
```

**Comment by jubalh** [comment]
Fixed with our merges from jasper-maint:

```
imginfo -f ~/jasper/out_of_bound_write                                                   :(
image too large
cannot load image
```

Not entirely sure which commit, and don't think git bisecting it is worth it here.
2.0.19 is thus fixed.
