### ISSUE TITLE
memory leak in jas_malloc.c

### ISSUE THREAD

**Issue by bestshow** [jasper-software/jasper#130]
on 2.0.12

```
#imginfo -f $FILE
=================================================================

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4dfd76 in __interceptor_malloc /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x7f503252de01 in jas_malloc /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/base/jas_malloc.c:242:11
    #2 0x7f503252e06c in jas_alloc2 /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/base/jas_malloc.c:275:9
    #3 0x7f5032571777 in jpc_dec_process_siz /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jpc/jpc_dec.c:1331:24
    #4 0x7f5032574cb0 in jpc_dec_decode /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jpc/jpc_dec.c:425:10
    #5 0x7f503257362e in jpc_decode /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jpc/jpc_dec.c:262:6
    #6 0x7f50325201d7 in jas_image_decode /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/base/jas_image.c:444:16
    #7 0x515ee5 in main /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/appl/imginfo.c:238:16
    #8 0x7f50315f7b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

128 byte(s) leaked in 1 allocation(s).
```

Testcase:
https://github.com/bestshow/p0cs/blob/master/1001-memleak-jas_malloc

**Comment by jubalh** [comment]
Fixed with our merges from jasper-maint:

```
imginfo -f ~/jasper/1001-memleak-jas_malloc 
invalid component bit depth 128
cannot get marker segment
cannot load image
```

Not entirely sure which commit, and don't think git bisecting it is worth it here.
