### ISSUE TITLE
J2C segmentation violation

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#306]
Oss-fuzz is detecting an issue with the J2C decoder:

```
       INFO: Running with entropic power schedule (0xFF, 100).
        INFO: Seed: 2870346876
        INFO: Loaded 1 modules   (229770 inline 8-bit counters): 229770 [0x1f464c0, 0x1f7e64a),
        INFO: Loaded 1 PC tables (229770 PCs): 229770 [0x1f7e650,0x22ffef0),
        /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_graphicsmagick_364babd4f1406e0e2b68256230a27a3911dd0072/revisions/coder_J2C_fuzzer: Running 1 inputs 100 time(s) each.
        Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-407ca1a47d8a85d6514b511d9d0adf378a0d1ab7
        AddressSanitizer:DEADLYSIGNAL
        =================================================================
        ==29047==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x000000e77999 bp 0x7fff5c182060 sp 0x7fff5c182030 T0)
        ==29047==The signal is caused by a READ memory access.
        ==29047==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
        SCARINESS: 20 (wild-addr-read)
            #0 0xe77999 in jpc_pchglist_destroy jasper/src/libjasper/jpc/jpc_t2cod.c:666:16
            #1 0xe45a98 in jpc_dec_cp_destroy jasper/src/libjasper/jpc/jpc_dec.c:1822:3
            #2 0xe45a98 in jpc_dec_cp_create jasper/src/libjasper/jpc/jpc_dec.c:1770:3
            #3 0xe3b0ca in jpc_dec_cp_copy jasper/src/libjasper/jpc/jpc_dec.c:1781:16
            #4 0xe3b0ca in jpc_dec_process_sot jasper/src/libjasper/jpc/jpc_dec.c:568:20
            #5 0xe38df4 in jpc_dec_decode jasper/src/libjasper/jpc/jpc_dec.c:436:10
            #6 0xe38df4 in jpc_decode jasper/src/libjasper/jpc/jpc_dec.c:270:6
            #7 0x9f6831 in ReadJP2Image graphicsmagick/coders/jp2.c:673:17
            #8 0x630378 in ReadImage graphicsmagick/magick/constitute.c:1630:13
            #9 0x5e0440 in BlobToImage graphicsmagick/magick/blob.c:764:13
            #10 0x56bfdd in Magick::Image::read(Magick::Blob const&) graphicsmagick/Magick++/lib/Image.cpp:1591:5
            #11 0x5615da in LLVMFuzzerTestOneInput graphicsmagick/fuzzing/coder_fuzzer.cc:22:15
            #12 0x458aa3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp:0
            #13 0x4443b2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
            #14 0x449e7a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp:0
            #15 0x472da2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
            #16 0x7f151465c0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
            #17 0x42163d in _start
        
        AddressSanitizer can not provide additional info.
        SUMMARY: AddressSanitizer: SEGV (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_graphicsmagick_364babd4f1406e0e2b68256230a27a3911dd0072/revisions/coder_J2C_fuzzer+0xe77999)
        ==29047==ABORTING
```
For some reason my local Jasper build does not seem to have 'j2c' support, otherwise I would provide info from the jasper utility.
I think that I may have run this on another system which has J2C enabled and valgrind detected use of uninitialized memory.

[clusterfuzz-testcase-coder_J2C_fuzzer-6230132319191040.gz](https://github.com/jasper-software/jasper/files/7577021/clusterfuzz-testcase-coder_J2C_fuzzer-6230132319191040.gz)

**Comment by mdadams** [comment]
I cannot reproduce this problem with the code on the master branch.
I ran:
 
    imginfo < /tmp/mdadams/clusterfuzz-testcase-coder_J2C_fuzzer-6230132319191040

The result I get is:

maximum number of samples exceeded (134184960 > 67108864)
jas_image_decode: decode operation failed
cannot load image

Then, I tried:

    imginfo --max-samples 2000000000 < /tmp/mdadams/clusterfuzz-testcase-coder_J2C_fuzzer-6230132319191040 

And I get:

jpc_dec_decodepkts failed
jas_image_decode: decode operation failed
cannot load image

The code does not crash.

**Comment by mdadams** [comment]
Other than bugs that are marked as unreproducible, I don't see any other bugs outstanding against JasPer at:
    https://bugs.chromium.org/p/oss-fuzz/issues/list?q=graphicsmagick
Since I also cannot reproduce the problem, I am going to assume that this issue is either a false positive or the other code changes that have been made to JasPer since the time that the fuzzer flagged this issue fixed the problem.  If the problem resurfaces, please let me know.
