### ISSUE TITLE
jas_initialize() allocates  a single buffer of 268,421,152 bytes and then aborts!

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#313]
Due to using jas_initialize() to register custom memory allocator functions, I have learned that invoking jas_initialize() performs many allocations via the custom memory allocator (expected), but also a very large one of 268,421,152 bytes (unexpected).  This counter-productive to the objective of limiting memory usage and providing a custom allocator.

To make matters worse, when the huge memory request fails, JasPer attempts to free the memory (good) but in the process, it aborts due to failing a pointer validity test.  If the memory limit is slightly increased, then there is no abort so it seems that there is some confusion in the failure-case clean-up code.

As it happens, for fuzz testing, we are using an over-all memory limit of 268,435,456 bytes and so JasPer's huge memory request fails.  The reason for using a relatively small memory limit for fuzz testing is that oss-fuzz has arbitrary time and memory limits, and there is often a relationship between memory usage and execution time.

```
Reading symbols from /home/bfriesen/build/GM-16-static-nothreads/utilities/gm...
(gdb) b jas_get_mb
Function "jas_get_mb" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (jas_get_mb) pending.
(gdb) r convert -debug coder -limit memory 268435456 -limit width 2048 -limit height 2048 -limit disk 0  JPC:clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504 info:-
Starting program: /home/bfriesen/build/GM-16-static-nothreads/utilities/gm convert -debug coder -limit memory 268435456 -limit width 2048 -limit height 2048 -limit disk 0  JPC:clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504 info:-
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
10:28:39 0:0.000195  0.000u 191547 constitute.c/ReadImage/1624/Coder:
  Invoking "JPC" decoder (JPEG-2000 Code Stream Syntax) subimage=0 subrange=0
10:28:39 0:0.000209  0.000u 191547 jp2.c/initialize_jasper/438/Coder:
  Initializing JasPer...

Breakpoint 1, 0x00007ffff7b2d9c2 in jas_get_mb () from /usr/local/lib/libjasper.so.7
(gdb) bt
#0  0x00007ffff7b2d9c2 in jas_get_mb () from /usr/local/lib/libjasper.so.7
#1  0x00007ffff7b2e366 in jas_basic_free () from /usr/local/lib/libjasper.so.7
#2  0x00007ffff7b2d545 in jas_free () from /usr/local/lib/libjasper.so.7
#3  0x00007ffff7b2cc1b in jas_init_codecs () from /usr/local/lib/libjasper.so.7
#4  0x00007ffff7b2cb24 in jas_init_helper () from /usr/local/lib/libjasper.so.7
#5  0x00007ffff7b2c9de in jas_initialize () from /usr/local/lib/libjasper.so.7
#6  0x0000555555712c49 in initialize_jasper () at /home/bfriesen/src/GM/coders/jp2.c:451
#7  0x0000555555713dc5 in ReadJP2Image (image_info=0x555555850a00, exception=0x7fffffffd790) at /home/bfriesen/src/GM/coders/jp2.c:550
#8  0x00005555555982d7 in ReadImage (image_info=image_info@entry=0x55555584c810, exception=exception@entry=0x7fffffffd790)
    at /home/bfriesen/src/GM/magick/constitute.c:1630
#9  0x000055555557c87b in ConvertImageCommand (image_info=0x55555584c810, argc=<optimized out>, argv=<optimized out>, metadata=0x0, 
    exception=0x7fffffffd790) at /home/bfriesen/src/GM/magick/command.c:4416
#10 0x000055555556e410 in MagickCommand (image_info=image_info@entry=0x55555584c810, argc=argc@entry=17, argv=argv@entry=0x7fffffffe130, 
    metadata=metadata@entry=0x7fffffffd788, exception=exception@entry=0x7fffffffd790) at /home/bfriesen/src/GM/magick/command.c:8916
#11 0x000055555556f23a in GMCommandSingle (argc=17, argc@entry=18, argv=0x7fffffffe130, argv@entry=0x7fffffffe128)
    at /home/bfriesen/src/GM/magick/command.c:17454
#12 0x000055555558d70f in GMCommand (argc=18, argv=0x7fffffffe128) at /home/bfriesen/src/GM/magick/command.c:17507
#13 0x0000555555566b26 in main (argc=<optimized out>, argv=<optimized out>) at /home/bfriesen/src/GM/utilities/gm.c:61
```

**Comment by bobfriesenhahn** [comment]
If I pass this additional initialization option:

```
jas_conf_set_max_mem(0);
```
then I get this error:

```
gm convert -debug coder -limit memory 268435456 -limit width 2048 -limit height 2048 -limit disk 0  JPC:clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504 info:-
13:29:18 0:0.000368  0.000u 281161 constitute.c/ReadImage/1624/Coder:
  Invoking "JPC" decoder (JPEG-2000 Code Stream Syntax) subimage=0 subrange=0
13:29:18 0:0.000382  0.000u 281161 jp2.c/initialize_jasper/438/Coder:
  Initializing JasPer...
maximum memory limit (0) would be exceeded
cannot initialize codecs
13:29:18 0:0.000394  0.000u 281161 jp2.c/initialize_jasper/471/Coder:
  Failed to initialize JasPer!
13:29:18 0:0.000406  0.000u 281161 jp2.c/ReadJP2Image/568/Coder:
  Requested format is "JPC"
maximum memory limit (0) would be exceeded
13:29:18 0:0.000417  0.000u 281161 constitute.c/ReadImage/1649/Coder:
  Returned from "JPC" decoder, returned image is NULL!
```

It appears that the custom memory allocator in the 3.0.0 code is currently not usable for its intended purpose.  Either it allocates the maximum memory in advance (consuming the maximum amount of resources which would ever be  used by the whole program) or else it refuses to work at all.

**Comment by mdadams** [comment]
Please run the code with the debug level set to at least 101 so that all memory allocations are traced, and include this output in your bug report.  This will help to pinpoint why the large allocation is being made.  Of course, JasPer does not allocate 256+ MB of memory just for fun.  Something is obviously wrong.

Also, as I have indicated before, the new customization/threading APIs are not yet stable.  So you may want to hold off on using them for now.  Otherwise, you will probably see breakage due to API changes.  I am hoping to find some time over the Christmas break to make some further progress on this issue.

**Comment by bobfriesenhahn** [comment]
Unfortunately, since the crash is in the first call to jas_initialize(), it does not appear that it is possible to enable JasPer debugging.  Obviously this would not work as a JasPer key/value option since it is not there yet.  So I tried using jas_setdbglevel(101) right before jas_initialize() and I get an immediate core dump.  The behavior is changed so I assume that jas_setdbglevel() needs jas_initialize() to have completed already.

Not to worry, I will continue to investigate. I have now built the library using your build script and it should hopefully have debug symbols.

**Comment by bobfriesenhahn** [comment]
I am thinking that the large memory allocation is due to the oss-fuzz test case I am using since it appears that the image component dimensions are large (128x524260).

```
Breakpoint 1, alloc_rlm (allocator=0x55555586a740 <allocator>, size=268421152) at /home/bfriesen/src/GM/coders/jp2.c:433
433       return _MagickAllocateResourceLimitedMemory(size == 0 ? 1 : size);
(gdb) bt
#0  alloc_rlm (allocator=0x55555586a740 <allocator>, size=268421152) at /home/bfriesen/src/GM/coders/jp2.c:433
#1  0x00007ffff7b45bd5 in jas_basic_alloc (allocator=0x7ffff7b82e20 <jas_basic_allocator>, size=268421120)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:443
#2  0x00007ffff7b46211 in jas_malloc (size=268421120) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:129
#3  0x00007ffff7b48655 in jas_stream_memopen (buf=buf@entry=0x0, bufsize=bufsize@entry=268421120)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:244
#4  0x00007ffff7b424d2 in jas_image_cmpt_create (tlx=0, tly=<optimized out>, hstep=1, vstep=1, width=128, height=524260, depth=25, sgnd=false, inmem=true)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_image.c:373
#5  0x00007ffff7b42ba3 in jas_image_create (numcmpts=<optimized out>, cmptparms=cmptparms@entry=0x55555589acd0, clrspc=clrspc@entry=16384)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_image.c:176
#6  0x00007ffff7b52757 in jpc_dec_process_sot (dec=0x555555899ef0, ms=0x55555589a010) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:516
#7  0x00007ffff7b53cb7 in jpc_dec_decode (dec=0x555555899ef0) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:436
#8  jpc_decode (in=<optimized out>, optstr=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:270
#9  0x000055555576b1d8 in ReadJP2Image (image_info=0x555555891d10, exception=0x7fffffffd750) at /home/bfriesen/src/GM/coders/jp2.c:728
#10 0x000055555559e16d in ReadImage (image_info=0x55555588da50, exception=0x7fffffffd750) at /home/bfriesen/src/GM/magick/constitute.c:1630
#11 0x000055555556cec0 in ConvertImageCommand (image_info=0x55555588da50, argc=19, argv=0x55555588fbb0, metadata=0x0, exception=0x7fffffffd750)
    at /home/bfriesen/src/GM/magick/command.c:4416
#12 0x000055555557799a in MagickCommand (image_info=0x55555588da50, argc=19, argv=0x7fffffffe0f0, metadata=0x7fffffffd738, exception=0x7fffffffd750)
    at /home/bfriesen/src/GM/magick/command.c:8916
#13 0x000055555558f597 in GMCommandSingle (argc=19, argv=0x7fffffffe0f0) at /home/bfriesen/src/GM/magick/command.c:17454
#14 0x000055555558f6c6 in GMCommand (argc=20, argv=0x7fffffffe0e8) at /home/bfriesen/src/GM/magick/command.c:17507
#15 0x000055555556375d in main (argc=20, argv=0x7fffffffe0e8) at /home/bfriesen/src/GM/utilities/gm.c:61

(gdb) c
Continuing.
gm: /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:318: jas_get_mb: Assertion `mb->magic == JAS_BMA_MAGIC' failed.
.
.
.
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7481859 in __GI_abort () at abort.c:79
#2  0x00007ffff7481729 in __assert_fail_base (fmt=0x7ffff7617588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7ffff7b701f2 "mb->magic == JAS_BMA_MAGIC", file=0x7ffff7b701b0 "/home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c", line=318, 
    function=<optimized out>) at assert.c:92
#3  0x00007ffff7492f06 in __GI___assert_fail (assertion=assertion@entry=0x7ffff7b701f2 "mb->magic == JAS_BMA_MAGIC", 
    file=file@entry=0x7ffff7b701b0 "/home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c", line=line@entry=318, 
    function=function@entry=0x7ffff7b70528 <__PRETTY_FUNCTION__.5238> "jas_get_mb") at assert.c:101
#4  0x00007ffff7b45d9b in jas_get_mb (ptr=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:318
#5  jas_get_mb (ptr=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:313
#6  0x00007ffff7b45dda in jas_basic_free (allocator=0x7ffff7b82e20 <jas_basic_allocator>, ptr=0x55555589b350)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:567
#7  0x00007ffff7b47170 in mem_close (obj=0x555555899e70) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:1349
#8  0x00007ffff7b48526 in jas_stream_close (stream=stream@entry=0x55555589b290) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:592
#9  0x00007ffff7b4eb01 in jpc_getms (in=0x555555896d00, cstate=cstate@entry=0x555555896770) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_cs.c:277
#10 0x00007ffff7b53c5c in jpc_dec_decode (dec=0x555555899ef0) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:418
#11 jpc_decode (in=<optimized out>, optstr=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:270
#12 0x000055555576b1d8 in ReadJP2Image (image_info=0x555555891d10, exception=0x7fffffffd750) at /home/bfriesen/src/GM/coders/jp2.c:728
#13 0x000055555559e16d in ReadImage (image_info=0x55555588da50, exception=0x7fffffffd750) at /home/bfriesen/src/GM/magick/constitute.c:1630
#14 0x000055555556cec0 in ConvertImageCommand (image_info=0x55555588da50, argc=19, argv=0x55555588fbb0, metadata=0x0, exception=0x7fffffffd750)
    at /home/bfriesen/src/GM/magick/command.c:4416
#15 0x000055555557799a in MagickCommand (image_info=0x55555588da50, argc=19, argv=0x7fffffffe0f0, metadata=0x7fffffffd738, exception=0x7fffffffd750)
    at /home/bfriesen/src/GM/magick/command.c:8916
#16 0x000055555558f597 in GMCommandSingle (argc=19, argv=0x7fffffffe0f0) at /home/bfriesen/src/GM/magick/command.c:17454
#17 0x000055555558f6c6 in GMCommand (argc=20, argv=0x7fffffffe0e8) at /home/bfriesen/src/GM/magick/command.c:17507
#18 0x000055555556375d in main (argc=20, argv=0x7fffffffe0e8) at /home/bfriesen/src/GM/utilities/gm.c:61
```
From the above, I see that JasPer is using its own jas_basic_allocator() to release the memory rather than the allocator registered by GraphicsMagick (free_rlm()).

What is interesting is that if there are no memory limits provided then this problem does not happen.  This suggests that use of JasPer's default memory allocator happens in an abnormal/error case.

**Comment by bobfriesenhahn** [comment]
Attaching oss-fuzz test case which triggers the issue:

[oss-fuzz-41154.tar.gz](https://github.com/jasper-software/jasper/files/7771483/oss-fuzz-41154.tar.gz)

**Comment by uvic-frodo** [comment]
jas_conf_set_max_mem(0) says do not allow any memory to be allocated.  You must set a limit greater than zero if you want to do anything useful.  For security (and performance) reasons, I do not allow users to opt out of the memory limit.  You can only change what the limit is.

**Comment by uvic-frodo** [comment]
The logging functionality is setup very early in jas_initialize so that log messages can be generated during initialization.  So, you should be able to get useful log messages during initialization.

**Comment by bobfriesenhahn** [comment]
This gdb backtrace shows the final call trace which failed to allocate.  It only requested 8224 bytes:

```
Breakpoint 2, _MagickReallocateResourceLimitedMemory (p=0x55555589b330, count=1, size=8224, clear=0) at /home/bfriesen/src/GM/magick/memory.c:785
785                   status = MagickFail;
(gdb) bt
#0  _MagickReallocateResourceLimitedMemory (p=0x55555589b330, count=1, size=8224, clear=0) at /home/bfriesen/src/GM/magick/memory.c:785
#1  0x000055555576a5e0 in realloc_rlm (allocator=0x55555586a740 <allocator>, pointer=0x55555589b330, new_size=8224) at /home/bfriesen/src/GM/coders/jp2.c:444
#2  0x00007ffff7b46036 in jas_basic_realloc (allocator=0x7ffff7b82e20 <jas_basic_allocator>, ptr=0x55555589b350, size=8192)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:532
#3  0x00007ffff7b462e7 in jas_realloc (ptr=0x55555589b350, size=size@entry=8192) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:151
#4  0x00007ffff7b464c4 in jas_realloc2 (ptr=<optimized out>, num_elements=num_elements@entry=8192, element_size=element_size@entry=1)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:210
#5  0x00007ffff7b4732c in mem_resize (bufsize=8192, m=0x555555899e70) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:1247
#6  mem_write (obj=0x555555899e70, buf=0x7fffffff89d0 "Q", cnt=8192) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:1282
#7  0x00007ffff7b48ba7 in jas_stream_write (cnt=8192, buf=0x7fffffff89d0, stream=0x55555589b290)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:728
#8  jas_stream_write (stream=0x55555589b290, buf=0x7fffffff89d0, cnt=8192) at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:707
#9  0x00007ffff7b48ccf in jas_stream_copy (out=out@entry=0x55555589b290, in=in@entry=0x555555896d00, n=20477)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:1114
#10 0x00007ffff7b4ea25 in jpc_getms (in=0x555555896d00, cstate=cstate@entry=0x555555896770) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_cs.c:275
#11 0x00007ffff7b53c5c in jpc_dec_decode (dec=0x555555899ef0) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:418
#12 jpc_decode (in=<optimized out>, optstr=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:270
#13 0x000055555576b1d8 in ReadJP2Image (image_info=0x555555891d10, exception=0x7fffffffd750) at /home/bfriesen/src/GM/coders/jp2.c:728
#14 0x000055555559e16d in ReadImage (image_info=0x55555588da50, exception=0x7fffffffd750) at /home/bfriesen/src/GM/magick/constitute.c:1630
#15 0x000055555556cec0 in ConvertImageCommand (image_info=0x55555588da50, argc=19, argv=0x55555588fbb0, metadata=0x0, exception=0x7fffffffd750)
    at /home/bfriesen/src/GM/magick/command.c:4416
#16 0x000055555557799a in MagickCommand (image_info=0x55555588da50, argc=19, argv=0x7fffffffe0f0, metadata=0x7fffffffd738, exception=0x7fffffffd750)
    at /home/bfriesen/src/GM/magick/command.c:8916
#17 0x000055555558f597 in GMCommandSingle (argc=19, argv=0x7fffffffe0f0) at /home/bfriesen/src/GM/magick/command.c:17454
#18 0x000055555558f6c6 in GMCommand (argc=20, argv=0x7fffffffe0e8) at /home/bfriesen/src/GM/magick/command.c:17507
#19 0x000055555556375d in main (argc=20, argv=0x7fffffffe0e8) at /home/bfriesen/src/GM/utilities/gm.c:61
```

**Comment by bobfriesenhahn** [comment]
I am attaching a JasPer debug trace which shows all of the memory allocation activity.  I see suspicious looking things at the end:

```
mem_resize(0x55d061c31e70, 8192)
jas_realloc(0x55d061c33350, 8192)
jas_basic_realloc(0x7f6740010e20, 0x55d061c33350, 8192)
jas_basic_realloc: old_mb=0x55d061c33330; old_ext_size=1056
jas_basic_realloc: realloc(0x55d060102740, 0x55d061c33330, 8224)
jas_basic_realloc(0x7f6740010e20, 0x55d061c33350, 8192) -> (nil) ((nil))
max_mem=1073741824; mem=268428433
jas_realloc: realloc(0x7f6740010e20, 0x55d061c33350, 8192) -> (nil)
mem_resize realloc failed
jas_stream_close(0x55d061c33290)
mem_close(0x55d061c31e70)
mem_close myalloc=1
mem_close freeing buffer 0x55d061c33350
jas_free(0x55d061c33350)
jas_basic_free(0x55d061c33350)
```

[jasper-debug.txt.gz](https://github.com/jasper-software/jasper/files/7771616/jasper-debug.txt.gz)

**Comment by uvic-frodo** [comment]
I think that the problem is that the reallocation operation does not have the same behavior as realloc in the failure case.  I think in the failure case of realloc, the block is supposed to be deemed NOT freed.  I think that the reallocate operation is freeing it in the failure case.  Would this be consistent with the problems that you see?

**Comment by bobfriesenhahn** [comment]
You are correct that realloc should not free the original allocation if the new allocation is not possible.  GraphicsMagick's wrapper does not do that.  If it was to do that then it would be failing horribly.

Did  you notice that the debugger reports that  JasPer is using its own jas_basic_allocator() to release the memory rather than the allocator registered by GraphicsMagick (free_rlm())?  The debugger does show which function is being called to deallocate memory (based on the function address) This seems to be the essence of the problem.

**Comment by bobfriesenhahn** [comment]
```
#6  0x00007ffff7b45dda in jas_basic_free (allocator=0x7ffff7b82e20 <jas_basic_allocator>, ptr=0x55555589b350)
    at /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:567
```

It is possible that I am misinterpreting the above.

**Comment by bobfriesenhahn** [comment]
Yes, I enabled instrumentation of when the GM provided allocators (with "rlm" in their names) are called and it appears that they are no longer called after the allocation has failed:

```
max_mem=1073741824; mem=268427169
jas_basic_alloc: alloc(0x556c42efd740, 136)
alloc_rlm(0x556c42efd740, 136) -> 0x556c44994270
jas_basic_alloc(0x7ff9f26afe20, 104) -> 0x556c44994290 (mb=0x556c44994270)
max_mem=1073741824; mem=268427305
jas_malloc(104) -> 0x556c44994290
jas_malloc(40)
jas_basic_alloc(0x7ff9f26afe20, 40)
max_mem=1073741824; mem=268427305
jas_basic_alloc: alloc(0x556c42efd740, 72)
alloc_rlm(0x556c42efd740, 72) -> 0x556c44992e50
jas_basic_alloc(0x7ff9f26afe20, 40) -> 0x556c44992e70 (mb=0x556c44992e50)
max_mem=1073741824; mem=268427377
jas_malloc(40) -> 0x556c44992e70
jas_malloc(1024)
jas_basic_alloc(0x7ff9f26afe20, 1024)
max_mem=1073741824; mem=268427377
jas_basic_alloc: alloc(0x556c42efd740, 1056)
alloc_rlm(0x556c42efd740, 1056) -> 0x556c44994330
jas_basic_alloc(0x7ff9f26afe20, 1024) -> 0x556c44994350 (mb=0x556c44994330)
max_mem=1073741824; mem=268428433
jas_malloc(1024) -> 0x556c44994350
jas_stream_memopen buffer buf=0x556c44994350 myalloc=1
jas_stream_read(0x556c4498fd00, 0x7ffe07bef8e0, 8192)
jas_stream_write(0x556c44994290, 0x7ffe07bef8e0, 8192)
mem_write(0x556c44992e70, 0x7ffe07bef8e0, 8192)
mem_write resizing from 1024 to 8192
mem_resize(0x556c44992e70, 8192)
jas_realloc(0x556c44994350, 8192)
jas_basic_realloc(0x7ff9f26afe20, 0x556c44994350, 8192)
jas_basic_realloc: old_mb=0x556c44994330; old_ext_size=1056
jas_basic_realloc: realloc(0x556c42efd740, 0x556c44994330, 8224)
realloc_rlm(0x556c42efd740, 0x556c44994330, 8224) -> (nil)
jas_basic_realloc(0x7ff9f26afe20, 0x556c44994350, 8192) -> (nil) ((nil))
max_mem=1073741824; mem=268428433
jas_realloc: realloc(0x7ff9f26afe20, 0x556c44994350, 8192) -> (nil)
mem_resize realloc failed
jas_stream_close(0x556c44994290)
mem_close(0x556c44992e70)
mem_close myalloc=1
mem_close freeing buffer 0x556c44994350
jas_free(0x556c44994350)
jas_basic_free(0x556c44994350)
gm: /home/bfriesen/src/jasper.git/src/libjasper/base/jas_malloc.c:318: jas_get_mb: Assertion `mb->magic == JAS_BMA_MAGIC' failed.
```

**Comment by bobfriesenhahn** [comment]
Interestingly, I only see the realloc_rlm() called once in the execution of the program.  And when it was called, it reported failure.

**Comment by bobfriesenhahn** [comment]
No "rlm" functions are mentioned as pertains to the jas_basic_free(0x556c44994350) which lead to the assertion in my latest core dump:

```
% fgrep 0x556c44994350 jasper-debug.txt
jas_basic_alloc(0x7ff9f26afe20, 1024) -> 0x556c44994350 (mb=0x556c44994330)
jas_malloc(1024) -> 0x556c44994350
jas_stream_memopen buffer buf=0x556c44994350 myalloc=1
jas_realloc(0x556c44994350, 8192)
jas_basic_realloc(0x7ff9f26afe20, 0x556c44994350, 8192)
jas_basic_realloc(0x7ff9f26afe20, 0x556c44994350, 8192) -> (nil) ((nil))
jas_realloc: realloc(0x7ff9f26afe20, 0x556c44994350, 8192) -> (nil)
mem_close freeing buffer 0x556c44994350
jas_free(0x556c44994350)
jas_basic_free(0x556c44994350)
```

It seems that two allocation systems must be active.

Something which may be of interest regarding the GraphicsMagick realloc() equivalent is that it reduces the number of reallocations by rounding small allocation sizes up.  This means that the returned pointer may sometimes be the same as the original pointer since the same underlying buffer was used.

**Comment by bobfriesenhahn** [comment]
The GraphicsMagick alloc_rlm, free_rlm, and realloc_rlm functions pay no attention to the 'struct jas_allocator_s *allocator' argument.  Hopefully this is not important.

**Comment by bobfriesenhahn** [comment]
It appears that the problem (starts to use a different memory allocator) happens after JasPer hits its default memory limit.  If I pass a huge value into jas_conf_set_max_mem() then the crash stops happening.  Instead I get this somewhat improved behavior:

```
18:15:29 0:0.000142  0.000u 178263 constitute.c/ReadImage/1624/Coder:
  Invoking "JPC" decoder (JPEG-2000 Code Stream Syntax) subimage=0 subrange=0
18:15:29 0:0.000155  0.000u 178263 jp2.c/initialize_jasper/464/Coder:
  Initializing JasPer...
18:15:29 0:0.000230  0.000u 178263 jp2.c/ReadJP2Image/625/Coder:
  Requested format is "JPC"
18:15:29 0:0.000243  0.000u 178263 jp2.c/ReadJP2Image/750/Coder:
  JP2 options = "debug=0 max_samples=268435456 "
18:15:29 0:0.000247  0.000u 178263 jp2.c/ReadJP2Image/770/Coder:
  Decoding JPC...
maximum memory limit (268435456) would be exceeded
cannot get marker segment
18:15:29 0:0.081459  0.080u 178263 constitute.c/ReadImage/1649/Coder:
  Returned from "JPC" decoder, returned image is NULL!
/home/bfriesen/build/GM-16-static-debug-noopenmp/utilities/gm convert: Unable to decode image file (clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504).
18:15:29 0:0.081483  0.080u 178263 jp2.c/cleanup_jasper/542/Coder:
  Destroying JasPer...
```
Notice the message about a "maximum memory limit (268435456) would be exceeded" which just happens to match the "max_samples=268435456" which was provided.  This is not re-assuring since it appears that a JasPer internal limiter was hit rather than being limited by the memory allocation functions.

The underlying bug which is hit after the first realloc fails likely remains.

**Comment by mdadams** [comment]
On Thu, 23 Dec 2021, Bob Friesenhahn wrote:
> The GraphicsMagick alloc_rlm, free_rlm, and realloc_rlm functions pay no
> attention to the 'struct jas_allocator_s *allocator' argument. Hopefully
> this is not important.

The allocator argument is only useful if you want your allocator object
to be stateful (i.e., to store state).

**Comment by uvic-frodo** [comment]
I'll let you know after I fix the reallocate operation to match the semantics of realloc in the standard library.  This problem will definitely hose things badly.

**Comment by bobfriesenhahn** [comment]
There will surely be more issues.  It is not common for the memory allocator to fail on modern systems so software does not get much testing for allocation failure in normal use.

I have a new oss-fuzz issue (42906) which shows that JasPer is de-referencing a null pointer during cleanup after an allocation failure.  JasPer's own limiter seems to have triggered.  This is part of the reported error output and and stack trace:

```
  | maximum memory limit (1073741824) would be exceeded
-- | --
  | AddressSanitizer:DEADLYSIGNAL
  | =================================================================
  | ==25865==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000000e472a6 bp 0x7ffe371fc5c0 sp 0x7ffe371fc4c0 T0)
  | ==25865==The signal is caused by a READ memory access.
  | ==25865==Hint: address points to the zero page.
  | SCARINESS: 10 (null-deref)
  | #0 0xe472a6 in jpc_dec_tilefini jasper/src/libjasper/jpc/jpc_dec.c:1080:16
  | #1 0xe39352 in jpc_dec_destroy jasper/src/libjasper/jpc/jpc_dec.c:2212:5
  | #2 0xe38b7c in jpc_decode jasper/src/libjasper/jpc/jpc_dec.c:0
  | #3 0x9f6273 in ReadJP2Image graphicsmagick/coders/jp2.c:681:17
```

**Comment by mdadams** [comment]
Although I could not reproduce the memory-allocator problems that you
are having with the specific test case that you provided, I have been
able to reproduce similar types of problems using my own experiments.
There were a few problems that I found.

THE MOST SERIOUS PROBLEM.
The most serious problem was that the "realloc" code in JasPer was not
correctly handling the realloc-failure case.  The code did not actually
free the block in the realloc-failure case (as I suggested before),
but rather it marked the block "as if" it had been freed (but did not
free it).  This is what led to the assertion failure that you
encountered regarding a BMA memory block signature being wrong.
This problem should now be fixed.  Assuming that there are no other
serious bugs lurking in the memory allocator, you should be okay now.

OTHER MEMORY-ALLOCATION-RELATED PROBLEMS.
The other problems that I found have nothing to due with the allocator
in a direct sense.  They are just bugs that have always been in the
code but were very unlikely to ever be hit until now.  The ability to
fail due to exceeding the memory limit causes many new failure modes,
which can expose previously-unhit bugs.  It seems that one of these
bugs overlaps with the null-pointer crash that you observed.

Anyways, please try out the new code on the master branch and let me
know if it fixes the problems that you are experiencing.
The relevant commit is 28c7a64ece3dab5477ead4972435f69de5659fb7.

**Comment by mdadams** [comment]
Another bug related to memory allocation has been fixed that caused jas_realloc to sometimes allocate a block that is slightly too small.  This has been fixed on the master branch.  If you use anything from the tag version-3.0.0-unstable3 onwards, this should eliminate all of the jas_realloc problems that you have been having.  So, I am going to close this issue.
