### ISSUE TITLE
Abort in jpc_qmfb_join_colgrp

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#314]
oss-fuzz 42959 found this issue (in conjunction with GraphicsMagick) and I am able to reproduce it:

```
(gdb) r convert -limit memory 268435456 -limit width 2048 -limit height 2048 -limit disk 0 -debug coder jp2:clusterfuzz-testcase-coder_JP2_fuzzer-5215626388439040 -verbose info:-
Starting program: /home/bfriesen/build/GM-16-static-debug-noopenmp/utilities/gm convert -limit memory 268435456 -limit width 2048 -limit height 2048 -limit disk 0 -debug coder jp2:clusterfuzz-testcase-coder_JP2_fuzzer-5215626388439040 -verbose info:-
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
16:17:41 0:0.000213  0.000u 849342 constitute.c/ReadImage/1624/Coder:
  Invoking "JP2" decoder (JPEG-2000 JP2 File Format Syntax) subimage=0 subrange=0
16:17:41 0:0.000229  0.000u 849342 jp2.c/initialize_jasper/464/Coder:
  Initializing JasPer...
16:17:41 0:0.000313  0.000u 849342 jp2.c/ReadJP2Image/625/Coder:
  Requested format is "JP2"
16:17:41 0:0.000325  0.000u 849342 jp2.c/ReadJP2Image/750/Coder:
  JP2 options = "max_samples=268435456 "
16:17:41 0:0.000330  0.000u 849342 jp2.c/ReadJP2Image/760/Coder:
  Decoding JP2...
warning: not enough tile data (1 bytes)
maximum memory limit (268435456) would be exceeded

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7336859 in __GI_abort () at abort.c:79
#2  0x00007ffff7b3b9b6 in jpc_qmfb_join_colgrp (a=0x7fffed6c6060, numrows=488191, stride=21, parity=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_qmfb.c:576
#3  0x00007ffff7b5b12f in jpc_ns_synthesize (a=<optimized out>, xstart=<optimized out>, ystart=5377, width=21, height=<optimized out>, stride=21)
    at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_qmfb.c:2200
#4  0x00007ffff7b66f7a in jpc_tsfb_synthesize (tsfb=<optimized out>, a=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_tsfb.c:168
#5  0x00007ffff7b50bf4 in jpc_dec_tiledecode (dec=dec@entry=0x55555594cec0, tile=tile@entry=0x55555594dd50) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:1208
#6  0x00007ffff7b53640 in jpc_dec_process_sod (dec=0x55555594cec0, ms=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:673
#7  0x00007ffff7b53d87 in jpc_dec_decode (dec=0x55555594cec0) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:436
#8  jpc_decode (in=in@entry=0x555555949a60, optstr=optstr@entry=0x555555949ad0 "max_samples=268435456 ") at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_dec.c:270
#9  0x00007ffff7b4c243 in jp2_decode (in=0x555555949a60, optstr=0x555555949ad0 "max_samples=268435456 ") at /home/bfriesen/src/jasper.git/src/libjasper/jp2/jp2_dec.c:231
#10 0x00005555557db78d in ReadJP2Image (image_info=0x555555944c50, exception=0x7fffffffd780) at /home/bfriesen/src/GM/coders/jp2.c:762
#11 0x00005555555acb7f in ReadImage (image_info=0x555555940a50, exception=0x7fffffffd780) at /home/bfriesen/src/GM/magick/constitute.c:1630
#12 0x00005555555742d5 in ConvertImageCommand (image_info=0x555555940a50, argc=18, argv=0x555555942bb0, metadata=0x0, exception=0x7fffffffd780) at /home/bfriesen/src/GM/magick/command.c:4416
#13 0x00005555555834ee in MagickCommand (image_info=0x555555940a50, argc=18, argv=0x7fffffffe120, metadata=0x7fffffffd768, exception=0x7fffffffd780) at /home/bfriesen/src/GM/magick/command.c:8916
#14 0x000055555559dfa9 in GMCommandSingle (argc=18, argv=0x7fffffffe120) at /home/bfriesen/src/GM/magick/command.c:17456
#15 0x000055555559e0d8 in GMCommand (argc=19, argv=0x7fffffffe118) at /home/bfriesen/src/GM/magick/command.c:17509
#16 0x0000555555567c5d in main (argc=19, argv=0x7fffffffe118) at /home/bfriesen/src/GM/utilities/gm.c:61
(gdb) frame 2
#2  0x00007ffff7b3b9b6 in jpc_qmfb_join_colgrp (a=0x7fffed6c6060, numrows=488191, stride=21, parity=<optimized out>) at /home/bfriesen/src/jasper.git/src/libjasper/jpc/jpc_qmfb.c:576
576                             abort();
(gdb) l
571             const size_t bufsize = JPC_CEILDIVPOW2(numrows, 1);
572             if (bufsize > QMFB_JOINBUFSIZE) {
573                     if (!(buf = jas_alloc3(bufsize, JPC_QMFB_COLGRPSIZE,
574                       sizeof(jpc_fix_t)))) {
575                             /* We have no choice but to commit suicide. */
576                             abort();
577                     }
578             }
579
580             const unsigned hstartcol = (numrows + !parity) >> 1;
```
Committing suicide is best left for others.

This is the oss-fuzz provided test case:

[clusterfuzz-testcase-coder_JP2_fuzzer-5215626388439040.gz](https://github.com/jasper-software/jasper/files/7777654/clusterfuzz-testcase-coder_JP2_fuzzer-5215626388439040.gz)

**Comment by mdadams** [comment]
I was able to reproduce and fix the problem. Yeah, aborting to handle errors is rather lame.
